/**
 * AI Service — provider priority (inspired by OmicsClaw multi-provider pattern):
 *   1. Groq         (VITE_GROQ_API_KEY)        — Llama 3.3 70B, free 14,400 req/day
 *   2. DeepSeek     (VITE_DEEPSEEK_API_KEY)     — DeepSeek-V3, ~$0 for light use
 *   3. Gemini       (VITE_GEMINI_API_KEY)        — 1.5 Flash, 1M tokens/day free
 *   4. OpenRouter   (VITE_OPENROUTER_API_KEY)   — free Llama/Gemma models
 *   5. Ollama       (localhost:11434)            — local, no key, unlimited
 *   6. Demo / mock  — always available, pre-written responses
 */

import Groq from 'groq-sdk';
import { getApiKey } from './settingsService';

export type AIProvider = 'groq' | 'deepseek' | 'gemini' | 'openrouter' | 'ollama' | 'demo';

export interface AIResponse {
  text: string;
  provider: AIProvider;
  model?: string;
}

const SYSTEM_PROMPT =
  'You are OncoCorr, an expert oncology & multi-omics research assistant. ' +
  'Provide concise, evidence-based answers about genes, cancer biology, ' +
  'biomarkers, pathway analysis, and clinical correlations. ' +
  'Use markdown formatting with **bold** for key terms.';

const DEMO_RESPONSES: Record<string, string> = {
  default: `**[Demo Mode — no API key configured]**

OncoCorr integrates multi-omics data to reveal gene co-expression and regulatory
correlations across cancer types. In real mode, this answer would be generated by
a live LLM analysing your specific query.

**Free providers you can configure (no credit card required):**
- **Groq** — groq.com → free 14,400 req/day (Llama 3.3 70B)
- **DeepSeek** — platform.deepseek.com → ~free for light use
- **Gemini** — aistudio.google.com → 1M tokens/day free
- **OpenRouter** — openrouter.ai → free Llama/Gemma models
- **Ollama** — local models, no key, unlimited

Add any key to your \`.env.local\` file, or click the **⚙ Settings** button in the header to enter a key directly in your browser.`,

  tp53_brca1: `**TP53 & BRCA1 — Oncology Context**

Both genes are critical tumour suppressors frequently co-mutated in high-grade
cancers. TP53 maintains genomic integrity via G1/S checkpoint regulation, while
BRCA1 orchestrates homologous recombination repair. Their co-inactivation is
associated with triple-negative breast cancer and high-grade serous ovarian
carcinoma. PARP inhibitors show synthetic lethality in BRCA1-deficient tumours,
especially when TP53 is also compromised.`,

  egfr_kras: `**EGFR & KRAS — Oncology Context**

EGFR and KRAS operate in the same RTK-RAS-MAPK signalling axis. KRAS mutations
(G12C, G12D) constitutively activate downstream signalling, bypassing EGFR
inhibition — explaining KRAS-mutant resistance to cetuximab/erlotinib.
In lung adenocarcinoma these mutations are mutually exclusive. KRAS G12C
inhibitors (sotorasib, adagrasib) are approved for KRAS-mutant NSCLC.`,

  myc_bcl2: `**MYC & BCL2 — Oncology Context**

MYC drives cellular proliferation through transcriptional amplification of growth
genes, while BCL2 suppresses apoptosis. Their co-overexpression creates a potent
oncogenic synergy seen in "double-hit" B-cell lymphomas. BCL2 inhibitor
venetoclax is now approved for CLL and AML; MYC inhibition remains challenging
but BET bromodomain inhibitors (e.g., JQ1) indirectly target MYC transcription.`,
};

function getDemoResponse(query: string): string {
  const q = query.toLowerCase();
  if ((q.includes('tp53') || q.includes('p53')) && (q.includes('brca1') || q.includes('brca')))
    return DEMO_RESPONSES.tp53_brca1;
  if (q.includes('egfr') && q.includes('kras')) return DEMO_RESPONSES.egfr_kras;
  if (q.includes('myc') && q.includes('bcl2')) return DEMO_RESPONSES.myc_bcl2;
  return DEMO_RESPONSES.default;
}

async function queryOpenAICompat(
  baseUrl: string,
  apiKey: string,
  model: string,
  prompt: string,
  extraHeaders: Record<string, string> = {},
): Promise<string> {
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      ...extraHeaders,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      max_tokens: 1024,
      temperature: 0.4,
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = (data?.choices?.[0]?.message?.content) as string | undefined;
  if (!text) throw new Error('Empty response');
  return text;
}

async function queryGroq(prompt: string): Promise<string> {
  const apiKey = getApiKey('groq') || (import.meta.env.VITE_GROQ_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No Groq key');
  const client = new Groq({ apiKey, dangerouslyAllowBrowser: true });
  const completion = await client.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
    max_tokens: 1024,
    temperature: 0.4,
  });
  const text = completion.choices[0]?.message?.content;
  if (!text) throw new Error('Empty Groq response');
  return text;
}

async function queryDeepSeek(prompt: string): Promise<string> {
  const apiKey = getApiKey('deepseek') || (import.meta.env.VITE_DEEPSEEK_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No DeepSeek key');
  return queryOpenAICompat('https://api.deepseek.com/v1', apiKey, 'deepseek-chat', prompt);
}

async function queryGemini(prompt: string): Promise<string> {
  const apiKey = getApiKey('gemini') || (import.meta.env.VITE_GEMINI_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No Gemini key');
  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: `${SYSTEM_PROMPT}\n\n${prompt}` }] }],
      generationConfig: { maxOutputTokens: 1024, temperature: 0.4 },
    }),
  });
  if (!res.ok) throw new Error(`Gemini HTTP ${res.status}`);
  const data = await res.json();
  const text = (data?.candidates?.[0]?.content?.parts?.[0]?.text) as string | undefined;
  if (!text) throw new Error('Empty Gemini response');
  return text;
}

async function queryOpenRouter(prompt: string): Promise<string> {
  const apiKey = getApiKey('openrouter') || (import.meta.env.VITE_OPENROUTER_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No OpenRouter key');
  return queryOpenAICompat(
    'https://openrouter.ai/api/v1',
    apiKey,
    (import.meta.env.VITE_OPENROUTER_MODEL as string | undefined) ||
      'meta-llama/llama-3.1-8b-instruct:free',
    prompt,
    { 'HTTP-Referer': 'https://oncorr.app', 'X-Title': 'OncoCorr' },
  );
}

async function queryOllama(prompt: string): Promise<string> {
  const base =
    (import.meta.env.VITE_OLLAMA_URL as string | undefined) || 'http://localhost:11434';
  const model =
    (import.meta.env.VITE_OLLAMA_MODEL as string | undefined) || 'llama3.2';
  const res = await fetch(`${base}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt: `${SYSTEM_PROMPT}\n\n${prompt}`, stream: false }),
  });
  if (!res.ok) throw new Error(`Ollama HTTP ${res.status}`);
  const data = await res.json();
  if (!data?.response) throw new Error('Empty Ollama response');
  return data.response as string;
}

export async function askAI(prompt: string): Promise<AIResponse> {
  const env = import.meta.env;
  if (getApiKey('groq') || env.VITE_GROQ_API_KEY) {
    try { return { text: await queryGroq(prompt), provider: 'groq', model: 'llama-3.3-70b' }; }
    catch (e) { console.warn('Groq failed:', e); }
  }
  if (getApiKey('deepseek') || env.VITE_DEEPSEEK_API_KEY) {
    try { return { text: await queryDeepSeek(prompt), provider: 'deepseek', model: 'deepseek-chat' }; }
    catch (e) { console.warn('DeepSeek failed:', e); }
  }
  if (getApiKey('gemini') || env.VITE_GEMINI_API_KEY) {
    try { return { text: await queryGemini(prompt), provider: 'gemini', model: 'gemini-1.5-flash' }; }
    catch (e) { console.warn('Gemini failed:', e); }
  }
  if (getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY) {
    try { return { text: await queryOpenRouter(prompt), provider: 'openrouter', model: 'llama-3.1-8b:free' }; }
    catch (e) { console.warn('OpenRouter failed:', e); }
  }
  try { return { text: await queryOllama(prompt), provider: 'ollama' }; }
  catch { /* not running locally */ }

  return { text: getDemoResponse(prompt), provider: 'demo' };
}

export function activeProvider(): AIProvider {
  const env = import.meta.env;
  if (getApiKey('groq') || env.VITE_GROQ_API_KEY) return 'groq';
  if (getApiKey('deepseek') || env.VITE_DEEPSEEK_API_KEY) return 'deepseek';
  if (getApiKey('gemini') || env.VITE_GEMINI_API_KEY) return 'gemini';
  if (getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY) return 'openrouter';
  return 'demo';
}
