/**
 * AI Service — provider priority (inspired by OmicsClaw multi-provider pattern):
 *   1. Groq         (VITE_GROQ_API_KEY)        — Llama 3.3 70B, free 14,400 req/day
 *   2. DeepSeek     (VITE_DEEPSEEK_API_KEY)     — DeepSeek-V3, ~$0 for light use
 *   3. Gemini       (VITE_GEMINI_API_KEY)        — 1.5 Flash, 1M tokens/day free
 *   4. OpenRouter   (VITE_OPENROUTER_API_KEY)   — free Llama/Gemma models
 *   5. Ollama       (localhost:11434)            — local, no key, unlimited
 *   6. Demo / mock  — always available, pre-written responses
 */

import Groq from 'groq-sdk';
import { getApiKey, getSelectedProvider } from './settingsService';

export type AIProvider = 'groq' | 'deepseek' | 'gemini' | 'openrouter' | 'ollama' | 'demo';

export interface AIResponse {
  text: string;
  provider: AIProvider;
  model?: string;
}

const CHART_FENCE = '```';
const SYSTEM_PROMPT =
  'You are OncoCorr, an expert oncology & multi-omics research assistant. ' +
  'Provide concise, evidence-based answers about genes, cancer biology, ' +
  'biomarkers, pathway analysis, and clinical correlations. ' +
  'Use markdown formatting with **bold** for key terms.\n\n' +
  'IMPORTANT — When the user asks for a chart, graph, heatmap, plot, or any visualization, ' +
  'you MUST respond with a special fenced code block that the app renders as a real interactive chart. ' +
  'Do NOT say you cannot make charts or graphs. Instead output:\n' +
  CHART_FENCE + 'chart\n' +
  '{"type":"bar","title":"Title","xLabel":"X axis","yLabel":"Y axis","data":[{"name":"Gene A","value":8.2}]}\n' +
  CHART_FENCE + '\n' +
  'Supported types and their required data shapes:\n' +
  '• "bar"     — data: [{"name":"Label","value":0}, ...]\n' +
  '• "line"    — data: [{"name":"Label","value":0}, ...]\n' +
  '• "scatter" — data: [{"x":0,"y":0}, ...]\n' +
  '• "heatmap" — genes: ["G1","G2",...], data: [{"row":"G1","col":"G2","value":0.75}, ...] ' +
  '(include every row×col pair)\n' +
  'Always fill in realistic, biologically-plausible numeric values. ' +
  'You may include explanatory text before and/or after the chart block.';

const DEMO_RESPONSES: Record<string, string> = {
  default: `**[Demo Mode — no API key configured]**

OncoCorr integrates multi-omics data to reveal gene co-expression and regulatory
correlations across cancer types. In real mode, this answer would be generated by
a live LLM analysing your specific query.

**Free providers you can configure (no credit card required):**
- **Groq** — groq.com → free 14,400 req/day (Llama 3.3 70B)
- **DeepSeek** — platform.deepseek.com → ~free for light use
- **Gemini** — aistudio.google.com → 1M tokens/day free
- **OpenRouter** — openrouter.ai → free Llama/Gemma models
- **Ollama** — local models, no key, unlimited

Add any key to your \`.env.local\` file, or click the **⚙ Settings** button in the header to enter a key directly in your browser.`,

  tp53_brca1: `**TP53 & BRCA1 — Oncology Context**

Both genes are critical tumour suppressors frequently co-mutated in high-grade
cancers. TP53 maintains genomic integrity via G1/S checkpoint regulation, while
BRCA1 orchestrates homologous recombination repair. Their co-inactivation is
associated with triple-negative breast cancer and high-grade serous ovarian
carcinoma. PARP inhibitors show synthetic lethality in BRCA1-deficient tumours,
especially when TP53 is also compromised.`,

  egfr_kras: `**EGFR & KRAS — Oncology Context**

EGFR and KRAS operate in the same RTK-RAS-MAPK signalling axis. KRAS mutations
(G12C, G12D) constitutively activate downstream signalling, bypassing EGFR
inhibition — explaining KRAS-mutant resistance to cetuximab/erlotinib.
In lung adenocarcinoma these mutations are mutually exclusive. KRAS G12C
inhibitors (sotorasib, adagrasib) are approved for KRAS-mutant NSCLC.`,

  myc_bcl2: `**MYC & BCL2 — Oncology Context**

MYC drives cellular proliferation through transcriptional amplification of growth
genes, while BCL2 suppresses apoptosis. Their co-overexpression creates a potent
oncogenic synergy seen in "double-hit" B-cell lymphomas. BCL2 inhibitor
venetoclax is now approved for CLL and AML; MYC inhibition remains challenging
but BET bromodomain inhibitors (e.g., JQ1) indirectly target MYC transcription.`,
};

function getDemoResponse(query: string): string {
  const q = query.toLowerCase();
  if ((q.includes('tp53') || q.includes('p53')) && (q.includes('brca1') || q.includes('brca')))
    return DEMO_RESPONSES.tp53_brca1;
  if (q.includes('egfr') && q.includes('kras')) return DEMO_RESPONSES.egfr_kras;
  if (q.includes('myc') && q.includes('bcl2')) return DEMO_RESPONSES.myc_bcl2;
  return DEMO_RESPONSES.default;
}

async function queryOpenAICompat(
  baseUrl: string,
  apiKey: string,
  model: string,
  prompt: string,
  extraHeaders: Record<string, string> = {},
): Promise<string> {
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      ...extraHeaders,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      max_tokens: 2048,
      temperature: 0.4,
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = (data?.choices?.[0]?.message?.content) as string | undefined;
  if (!text) throw new Error('Empty response');
  return text;
}

async function queryGroq(prompt: string): Promise<string> {
  const apiKey = getApiKey('groq') || (import.meta.env.VITE_GROQ_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No Groq key');
  const client = new Groq({ apiKey, dangerouslyAllowBrowser: true });
  const completion = await client.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
    max_tokens: 2048,
    temperature: 0.4,
  });
  const text = completion.choices[0]?.message?.content;
  if (!text) throw new Error('Empty Groq response');
  return text;
}

async function queryDeepSeek(prompt: string): Promise<string> {
  const apiKey = getApiKey('deepseek') || (import.meta.env.VITE_DEEPSEEK_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No DeepSeek key');
  return queryOpenAICompat('https://api.deepseek.com/v1', apiKey, 'deepseek-chat', prompt);
}

async function queryGemini(prompt: string): Promise<string> {
  const apiKey = getApiKey('gemini') || (import.meta.env.VITE_GEMINI_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No Gemini key');
  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: `${SYSTEM_PROMPT}\n\n${prompt}` }] }],
      generationConfig: { maxOutputTokens: 2048, temperature: 0.4 },
    }),
  });
  if (!res.ok) throw new Error(`Gemini HTTP ${res.status}`);
  const data = await res.json();
  const text = (data?.candidates?.[0]?.content?.parts?.[0]?.text) as string | undefined;
  if (!text) throw new Error('Empty Gemini response');
  return text;
}

async function queryOpenRouter(prompt: string): Promise<string> {
  const apiKey = getApiKey('openrouter') || (import.meta.env.VITE_OPENROUTER_API_KEY as string | undefined);
  if (!apiKey) throw new Error('No OpenRouter key');
  return queryOpenAICompat(
    'https://openrouter.ai/api/v1',
    apiKey,
    (import.meta.env.VITE_OPENROUTER_MODEL as string | undefined) ||
      'meta-llama/llama-3.1-8b-instruct:free',
    prompt,
    { 'HTTP-Referer': 'https://oncorr.app', 'X-Title': 'OncoCorr' },
  );
}

async function queryOllama(prompt: string): Promise<string> {
  const base =
    (import.meta.env.VITE_OLLAMA_URL as string | undefined) || 'http://localhost:11434';
  const model =
    (import.meta.env.VITE_OLLAMA_MODEL as string | undefined) || 'llama3.2';
  const res = await fetch(`${base}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model, prompt: `${SYSTEM_PROMPT}\n\n${prompt}`, stream: false }),
  });
  if (!res.ok) throw new Error(`Ollama HTTP ${res.status}`);
  const data = await res.json();
  if (!data?.response) throw new Error('Empty Ollama response');
  return data.response as string;
}

/** Result returned by {@link testProvider}. */
export interface ProviderTestResult {
  ok: boolean;
  /** Human-readable error message when ok is false. */
  error?: string;
}

/**
 * Test a provider key by sending a minimal prompt.
 * Uses the key supplied in the argument (not the saved localStorage key),
 * so callers can test before saving.
 */
export async function testProvider(
  provider: keyof import('./settingsService').ApiKeys | 'ollama',
  key: string,
): Promise<ProviderTestResult> {
  const TEST_PROMPT = 'Reply with a single word: OK';
  try {
    switch (provider) {
      case 'groq': {
        const client = new Groq({ apiKey: key, dangerouslyAllowBrowser: true });
        const c = await client.chat.completions.create({
          model: 'llama-3.3-70b-versatile',
          messages: [{ role: 'user', content: TEST_PROMPT }],
          max_tokens: 10,
          temperature: 0,
        });
        if (!c.choices[0]?.message?.content) throw new Error('Empty response');
        break;
      }
      case 'deepseek':
        await queryOpenAICompat('https://api.deepseek.com/v1', key, 'deepseek-chat', TEST_PROMPT);
        break;
      case 'gemini': {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`;
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: TEST_PROMPT }] }],
            generationConfig: { maxOutputTokens: 10 },
          }),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
        break;
      }
      case 'openrouter':
        await queryOpenAICompat(
          'https://openrouter.ai/api/v1',
          key,
          'meta-llama/llama-3.1-8b-instruct:free',
          TEST_PROMPT,
          { 'HTTP-Referer': 'https://oncorr.app', 'X-Title': 'OncoCorr' },
        );
        break;
      case 'ollama': {
        const base = (import.meta.env.VITE_OLLAMA_URL as string | undefined) || 'http://localhost:11434';
        const model = (import.meta.env.VITE_OLLAMA_MODEL as string | undefined) || 'llama3.2';
        const res = await fetch(`${base}/api/generate`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ model, prompt: TEST_PROMPT, stream: false }),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        break;
      }
    }
    return { ok: true };
  } catch (e) {
    return { ok: false, error: humaniseError(e) };
  }
}

function humaniseError(e: unknown): string {
  const msg = e instanceof Error ? e.message : String(e);
  if (msg.toLowerCase().includes('failed to fetch') || msg.includes('NetworkError') || msg.includes('Load failed')) {
    return 'Network / CORS error — check your connection or whether the API allows browser requests';
  }
  return msg;
}

export async function askAI(prompt: string): Promise<AIResponse> {
  const env = import.meta.env;
  const selected = getSelectedProvider();
  const failures: Array<{ name: string; error: string }> = [];

  // Helper: try a specific provider and return its result (throws on failure)
  async function tryProvider(provider: AIProvider): Promise<AIResponse | null> {
    switch (provider) {
      case 'groq':
        if (getApiKey('groq') || env.VITE_GROQ_API_KEY)
          return { text: await queryGroq(prompt), provider: 'groq', model: 'llama-3.3-70b' };
        break;
      case 'deepseek':
        if (getApiKey('deepseek') || env.VITE_DEEPSEEK_API_KEY)
          return { text: await queryDeepSeek(prompt), provider: 'deepseek', model: 'deepseek-chat' };
        break;
      case 'gemini':
        if (getApiKey('gemini') || env.VITE_GEMINI_API_KEY)
          return { text: await queryGemini(prompt), provider: 'gemini', model: 'gemini-1.5-flash' };
        break;
      case 'openrouter':
        if (getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY)
          return { text: await queryOpenRouter(prompt), provider: 'openrouter', model: 'llama-3.1-8b:free' };
        break;
      case 'ollama':
        return { text: await queryOllama(prompt), provider: 'ollama' };
    }
    return null;
  }

  async function tryWithTracking(provider: AIProvider): Promise<AIResponse | null> {
    try {
      return await tryProvider(provider);
    } catch (e) {
      // Only record failures for providers that actually had a key and were called
      const hadKey =
        provider === 'ollama' ||
        (provider === 'groq'       && !!(getApiKey('groq')       || env.VITE_GROQ_API_KEY))       ||
        (provider === 'deepseek'   && !!(getApiKey('deepseek')   || env.VITE_DEEPSEEK_API_KEY))   ||
        (provider === 'gemini'     && !!(getApiKey('gemini')     || env.VITE_GEMINI_API_KEY))     ||
        (provider === 'openrouter' && !!(getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY));
      if (hadKey) failures.push({ name: provider, error: humaniseError(e) });
      console.warn(`${provider} failed:`, e);
      return null;
    }
  }

  // If the user has explicitly chosen a provider, try it first
  if (selected !== 'auto') {
    const result = await tryWithTracking(selected as AIProvider);
    if (result) return result;
  }

  // Auto-priority fallback
  const order: AIProvider[] = ['groq', 'deepseek', 'gemini', 'openrouter', 'ollama'];
  for (const provider of order) {
    if (selected !== 'auto' && provider === (selected as AIProvider)) continue; // already tried
    const result = await tryWithTracking(provider);
    if (result) return result;
  }

  // All providers exhausted — build an informative fallback response
  const errorSection = failures.length > 0
    ? `**⚠️ Configured provider(s) failed — showing demo response**\n\n` +
      `The following provider(s) returned an error:\n` +
      failures.map(({ name, error }) => `- **${name}**: \`${error}\``).join('\n') +
      `\n\nPlease check your API keys in ⚙ Settings, or open the browser console (F12) for full details.\n\n---\n\n`
    : '';

  return { text: errorSection + getDemoResponse(prompt), provider: 'demo' };
}

export function activeProvider(): AIProvider {
  const env = import.meta.env;
  const selected = getSelectedProvider();
  if (selected !== 'auto') {
    // Validate that the selected provider still has a key
    const hasKey: Record<string, boolean> = {
      groq: !!(getApiKey('groq') || env.VITE_GROQ_API_KEY),
      deepseek: !!(getApiKey('deepseek') || env.VITE_DEEPSEEK_API_KEY),
      gemini: !!(getApiKey('gemini') || env.VITE_GEMINI_API_KEY),
      openrouter: !!(getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY),
      ollama: true,
    };
    if (hasKey[selected]) return selected as AIProvider;
  }
  if (getApiKey('groq') || env.VITE_GROQ_API_KEY) return 'groq';
  if (getApiKey('deepseek') || env.VITE_DEEPSEEK_API_KEY) return 'deepseek';
  if (getApiKey('gemini') || env.VITE_GEMINI_API_KEY) return 'gemini';
  if (getApiKey('openrouter') || env.VITE_OPENROUTER_API_KEY) return 'openrouter';
  return 'demo';
}
